//Prueba
export const ACTUALIZAR_PRUEBA = 'ACTUALIZAR_PRUEBA';

//Album
export const ACTUALIZAR_ALBUM = 'ACTUALIZAR_ALBUM'
export const ACTUALIZAR_SELECTED_ALBUM = 'ACTUALIZAR_SELECTED_ALBUM'

//AlbumDetail
export const ACTUALIZAR_DETALLES = 'ACTUALIZAR_DETALLES'